
title: "gram.js"
description: "Gram is a textual format for data graphs."

twitter_username: akollegger
github_username:  akollegger
repository: gram-data/gram-js

permalink: pretty

show_excerpts: true

defaults:  
  - scope:
      path: ""
    values:
      layout: "guides"

exclude:  
  - "*.config.js"
  - "package*.json"
  - "node_modules"

collections:
  guides:
    output: true

highlighter: rouge

kramdown:
  syntax_highlighter: rouge
  input: GFM

social_links:
  twitter: akollegger
  github: gram-data
  stackoverflow: gram
  keybase: akollegger

plugins:
  - rouge
  - jekyll-feed
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - "jekyll-github-metadata"